
path: /Users/deepshikhar/Documents/My_Projects/Sign_Lang_Recognition/data  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes
nc: 7
names: ['hello','namaste','no','please','sorry','thanks','yes']
